[env:RONGO_node]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115000
board_upload.flash_size = 4MB
board_build.partitions = default.csv
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    SPI
